[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.0",
    "cmake>=3.18"
]
build-backend = "setuptools.build_meta"

[project]
name = "dr_sasa_py"
version = "0.1.0"
description = "Python bindings for SASA calculations"
authors = [
    {name = "xxx", email = "xx"}
]
requires-python = ">=3.7,<3.13" 
readme = "README.md"
license = {text = "MIT"}

dependencies = [
    "numpy>=1.26.0",
    "pandas>=2.1.0",
    "pybind11>=2.6.0",
    "pytest>=7.0.0",
    "ipykernel",
    "notebook"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]